spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gzhipin?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    sql-script-encoding: UTF-8
    separator: ;
    initialization-mode: always